#!/bin/bash

#SBATCH --account=coreai_dlalgo_nemorl
#SBATCH --exclusive
#SBATCH --partition=interactive
#SBATCH --job-name=fp8_is_qwen3-8b
#SBATCH --mail-type=ALL
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=2
#SBATCH --gres=gpu:8
#SBATCH --time=3:59:00
#SBATCH --output=./slurm/%j.out
#SBATCH --error=./slurm/%j.err
##SBATCH --overcommit

set -x

# CONTAINER="nvcr.io/r2kuatviomfd/internal-sandbox/nemo-rl-ngc:0919"
CONTAINER="/lustre/fsw/portfolios/coreai/users/larkz/docker_images/nemo-rl-sep25.sqsh"
MOUNTS=""
current_dir=$(pwd)
MOUNTS+="${current_dir}/..:/apps"
export HF_HOME=/apps/.cache


current_time=$(date +"%Y%m%d_%H%M")
WBPROJECT=verl_${current_time}
echo $WBPROJECT

# Necessary Exports
export HYDRA_FULL_ERROR=1
#export TRANSFORMERS_OFFLINE=1
export NCCL_AVOID_RECORD_STREAMS=1
#export ENROOT_ROOTFS_WRITABLE=1


JOBLOG="$(realpath .)/qwen3-8b-fp8-is-2node-$SLURM_JOB_ID.log"
echo "$(date '+%Y-%m-%d %H:%M:%S') Job ${SLURM_JOB_ID} started ..." &>> ${JOBLOG}

# launch ray daemon
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST") # Getting the node names
nodes_array=( $nodes )
node_1=${nodes_array[0]}
ip=$node_1

port=6379
ip_head=$ip:$port
export ip_head
echo "IP Head: $ip_head"  &>> ${JOBLOG}

echo "STARTING HEAD at $node_1"  &>> ${JOBLOG}
srun --nodes=1 --ntasks=1 -w "$node_1" --container-image="$CONTAINER" --no-container-mount-home --container-mounts="$MOUNTS" bash -c \
    "ray start --head --node-ip-address=$ip --port=$port --block" &>> ${JOBLOG} &
sleep 10s

worker_num=$((SLURM_JOB_NUM_NODES)) #number of nodes other than the head node
for ((i = 1; i < worker_num; i++)); do
node_i=${nodes_array[$i]}
echo "STARTING WORKER $i at $node_i"  &>> ${JOBLOG}
srun --nodes=1 --ntasks=1 -w "$node_i" --container-image="$CONTAINER" --no-container-mount-home --container-mounts="$MOUNTS" bash -c \
    "ray start --address $ip_head --block" &>> ${JOBLOG} &
sleep 1s
done

sleep 30s


read -r -d '' cmd <<EOF
echo "*******STARTING********" \
&& echo "---------------" \
&& ray status \
&& export WANDB_API_KEY=149737fd3c4537b349a37aab90b6fff96f385ebc \
&& export HF_HOME=/apps/.cache \
&& cd /apps/RL/ \
&& uv run examples/run_grpo_math.py --config examples/configs/recipes/llm/qwen3-2n/grpo-qwen3-8b-2n8g-megatron-fp8-dapo-is.yaml
EOF


# ===== submit ray job =====
# Job start
srun --overlap --nodes=1 --ntasks=1 -w "$node_1" --container-image="$CONTAINER" --no-container-mount-home --container-mounts="$MOUNTS" bash -c \
    "$cmd" &>> ${JOBLOG}

echo "$(date '+%Y-%m-%d %H:%M:%S') Job ${SLURM_JOB_ID} stopped ..." &>> ${JOBLOG}

