#!/bin/bash

#SBATCH --account=coreai_dlalgo_nemorl
#SBATCH --exclusive
#SBATCH --partition=interactive
#SBATCH --job-name=verl_fp8
#SBATCH --mail-type=ALL
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=1
#SBATCH --gres=gpu:8
#SBATCH --time=3:59:00
#SBATCH --output=./slurm/%j.out
#SBATCH --error=./slurm/%j.err
##SBATCH --overcommit

set -x

# CONTAINER="nvcr.io/nvidia/pytorch:25.04-py3"
# CONTAINER="nvcr.io/r2kuatviomfd/nemo-rl-release:latest"
# CONTAINER="/lustre/fsw/portfolios/coreai/users/shuangy/images/nemo-rl-main-250825.sqsh"
CONTAINER="verlai/verl:app-verl0.5-transformers4.55.4-sglang0.4.10.post2-mcore0.13.0-te2.2"

MOUNTS=""
current_dir=$(pwd)
MOUNTS+="${current_dir}/..:/apps"

current_time=$(date +"%Y%m%d_%H%M")
WBPROJECT=verl_${current_time}
echo $WBPROJECT

# Necessary Exports
export HYDRA_FULL_ERROR=1
#export TRANSFORMERS_OFFLINE=1
export NCCL_AVOID_RECORD_STREAMS=1
#export ENROOT_ROOTFS_WRITABLE=1

# && ray start --head --node-ip-address 0.0.0.0 --num-gpus 8 \
# && sh examples/scripts/train_distill_grpo_ray_hybrid_engine.sh


read -r -d '' cmd <<EOF
echo "*******STARTING********" \
&& echo "---------------" \
&& echo "Starting training" \
&& CUDA_DEVICE_MAX_CONNECTIONS=1 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
&& nvidia-smi \
&& whoami \
&& set -x \
&& pwd \
&& tail -f /dev/null
EOF


# --container-save=/lustre/fsw/general_sa/larkz/docker_images/verl.sqsh
# --container-save=/lustre/fsw/portfolios/coreai/users/larkz/dockers/nemorl.sqsh
srun --container-image ${CONTAINER} --container-save=/lustre/fsw/portfolios/coreai/users/larkz/docker_images/verl_sglang.sqsh --no-container-mount-home --container-name ${WBPROJECT} --container-mounts ${MOUNTS} bash -c "${cmd}"

set +x
